name: build-images

on:
  push:
    branches:
      - "main"
      - "feature/alpineVersionPerAnsibleVersion"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - { ansible: 2.10.0, alpine: 3.15 }
          - { ansible: 3.4.0, alpine: 3.15 }
          - { ansible: 4.8.0, alpine: 3.15 }
          - { ansible: 4.10.0, alpine: 3.15 }
          - { ansible: 5.5.0, alpine: 3.15 }
          - { ansible: 5.8.0, alpine: 3.15 }
          - { ansible: 5.10.0, alpine: 3.15 }
          - { ansible: 6.7.0, alpine: 3.15 }
          - { ansible: 7.7.0, alpine: 3.15 }
          - { ansible: 8.7.0, alpine: 3.15 }
          - { ansible: 9.7.0, alpine: 3.15 }
          - { ansible: 10.1.0, alpine: 3.15 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ANSIBLE_VERSION=${{ matrix.versions.ansible }}
            BASE_IMAGE=alpine:${{ matrix.versions.alpine }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: rareloop/ansible:${{ matrix.versions.ansible }}
